### ISSUE TITLE
Чистота кода

### ISSUE THREAD

**Issue by alexmikhalevich** [ValeryStatinov/Patterns_project#2]
Строка судя по контексту должна передаваться по ссылке на константный объект. Лишние копии ни к чему.
https://github.com/ValeryStatinov/Patterns_project/blob/e5a12b259e6f66ec5a5f3fea4834612a4a5ac4c4/Entity.h#L17

**Comment by ValeryStatinov** [comment]
подправил в тех местах, где нашел ошибки
